### ISSUE TITLE
Unresolved dependency

### ISSUE THREAD

**Issue by ajhcpt** [lihaoyi/workbench-example-app#30]
Get this when running sbt ~fastOptJS:

[info] Loading project definition from E:\Projects\workbench-example-app\project
[info] Updating {file:/E:/Projects/workbench-example-app/project/}workbench-example-app-build...
[info] Resolving org.scala-js#sbt-scalajs;0.6.6 ...
[info] Resolving org.scala-js#scalajs-tools_2.10;0.6.6 ...
[info] Resolving org.scala-lang#scala-library;2.10.4 ...
[info] Resolving org.scala-js#scalajs-ir_2.10;0.6.6 ...
[info] Resolving com.google.javascript#closure-compiler;v20130603 ...
[info] Resolving args4j#args4j;2.0.16 ...
[info] Resolving com.google.guava#guava;14.0.1 ...
[info] Resolving com.google.protobuf#protobuf-java;2.4.1 ...
[info] Resolving org.json#json;20090211 ...
[info] Resolving com.google.code.findbugs#jsr305;1.3.9 ...
[info] Resolving com.googlecode.json-simple#json-simple;1.1.1 ...
[info] Resolving junit#junit;4.10 ...
[info] Resolving org.hamcrest#hamcrest-core;1.1 ...
[info] Resolving org.scala-js#scalajs-js-envs_2.10;0.6.6 ...
[info] Resolving io.apigee#rhino;1.7R5pre4 ...
[info] Resolving org.webjars#envjs;1.2 ...
[info] Resolving org.scala-js#scalajs-sbt-test-adapter_2.10;0.6.6 ...
[info] Resolving org.scala-sbt#test-interface;1.0 ...
[info] Resolving com.lihaoyi#workbench;0.2.3 ...
[info] Resolving com.lihaoyi#workbench;0.2.3 ...
[warn]  module not found: com.lihaoyi#workbench;0.2.3
[warn] ==== typesafe-ivy-releases: tried
[warn]   https://repo.typesafe.com/typesafe/ivy-releases/com.lihaoyi/workbench/scala_2.10/sbt_0.13/0.2.3/ivys/ivy.xml
[warn] ==== sbt-plugin-releases: tried
[warn]   https://repo.scala-sbt.org/scalasbt/sbt-plugin-releases/com.lihaoyi/workbench/scala_2.10/sbt_0.13/0.2.3/ivys/ivy.xml
[warn] ==== local: tried
[warn]   C:\Users\andrewhe.ivy2\local\com.lihaoyi\workbench\scala_2.10\sbt_0.13\0.2.3\ivys\ivy.xml
[warn] ==== artifactory-ivy-proxy-releases: tried
[warn]   https://theluggage-agct.gray.net/artifactory/ivy-remote-repo/com.lihaoyi/workbench/scala_2.10/sbt_0.13/0.2.3/ivys/ivy.xml
[warn] ==== artifactory-maven-proxy-releases: tried
[warn]   https://theluggage-agct.gray.net/artifactory/maven-remote-repo/com/lihaoyi/workbench_2.10_0.13/0.2.3/workbench-0.2.3.pom
[info] Resolving org.scala-sbt#sbt;0.13.7 ...
[info] Resolving org.scala-sbt#main;0.13.7 ...
[info] Resolving org.scala-sbt#actions;0.13.7 ...
[info] Resolving org.scala-sbt#classpath;0.13.7 ...
[info] Resolving org.scala-lang#scala-compiler;2.10.4 ...
[info] Resolving org.scala-lang#scala-reflect;2.10.4 ...
[info] Resolving org.scala-sbt#launcher-interface;0.13.7 ...
[info] Resolving org.scala-sbt#interface;0.13.7 ...
[info] Resolving org.scala-sbt#io;0.13.7 ...
[info] Resolving org.scala-sbt#control;0.13.7 ...
[info] Resolving org.scala-sbt#completion;0.13.7 ...
[info] Resolving org.scala-sbt#collections;0.13.7 ...
[info] Resolving jline#jline;2.11 ...
[info] Resolving org.scala-sbt#api;0.13.7 ...
[info] Resolving org.scala-sbt#compiler-integration;0.13.7 ...
[info] Resolving org.scala-sbt#incremental-compiler;0.13.7 ...
[info] Resolving org.scala-sbt#logging;0.13.7 ...
[info] Resolving org.scala-sbt#process;0.13.7 ...
[info] Resolving org.scala-sbt#relation;0.13.7 ...
[info] Resolving org.scala-sbt#compile;0.13.7 ...
[info] Resolving org.scala-sbt#persist;0.13.7 ...
[info] Resolving org.scala-tools.sbinary#sbinary_2.10;0.4.2 ...
[info] Resolving org.scala-sbt#classfile;0.13.7 ...
[info] Resolving org.scala-sbt#compiler-ivy-integration;0.13.7 ...
[info] Resolving org.scala-sbt#ivy;0.13.7 ...
[info] Resolving org.scala-sbt#cross;0.13.7 ...
[info] Resolving org.scala-sbt.ivy#ivy;2.3.0-sbt-fccfbd44c9f64523b61398a0155784dcbaeae28f ...
[info] Resolving com.jcraft#jsch;0.1.46 ...
[info] Resolving org.json4s#json4s-native_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-core_2.10;3.2.10 ...
[info] Resolving org.json4s#json4s-ast_2.10;3.2.10 ...
[info] Resolving com.thoughtworks.paranamer#paranamer;2.6 ...
[info] Resolving org.scala-lang#scalap;2.10.0 ...
[info] Resolving org.spire-math#jawn-parser_2.10;0.6.0 ...
[info] Resolving org.spire-math#json4s-support_2.10;0.6.0 ...
[info] Resolving org.scala-sbt#run;0.13.7 ...
[info] Resolving org.scala-sbt#task-system;0.13.7 ...
[info] Resolving org.scala-sbt#tasks;0.13.7 ...
[info] Resolving org.scala-sbt#tracking;0.13.7 ...
[info] Resolving org.scala-sbt#cache;0.13.7 ...
[info] Resolving org.scala-sbt#testing;0.13.7 ...
[info] Resolving org.scala-sbt#test-agent;0.13.7 ...
[info] Resolving org.scala-sbt#main-settings;0.13.7 ...
[info] Resolving org.scala-sbt#apply-macro;0.13.7 ...
[info] Resolving org.scala-sbt#command;0.13.7 ...
[info] Resolving org.scala-sbt#logic;0.13.7 ...
[info] Resolving org.scala-sbt#compiler-interface;0.13.7 ...
[info] Resolving org.scala-sbt#precompiled-2_8_2;0.13.7 ...
[info] Resolving org.scala-sbt#precompiled-2_9_2;0.13.7 ...
[info] Resolving org.scala-sbt#precompiled-2_9_3;0.13.7 ...
[info] Resolving org.scala-lang#jline;2.10.4 ...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.lihaoyi#workbench;0.2.3: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn]  Note: Some unresolved dependencies have extra attributes.  Check that these dependencies exist with the requested attributes.
[warn]      com.lihaoyi:workbench:0.2.3 (sbtVersion=0.13, scalaVersion=2.10)
[warn] 
[warn]  Note: Unresolved dependencies path:
[warn]      com.lihaoyi:workbench:0.2.3 (sbtVersion=0.13, scalaVersion=2.10) (E:\Projects\workbench-example-app\project\build.sbt#L3-4)
[warn]        +- default:workbench-example-app-build:0.1-SNAPSHOT (sbtVersion=0.13, scalaVersion=2.10)
sbt.ResolveException: unresolved dependency: com.lihaoyi#workbench;0.2.3: not found
    at sbt.IvyActions$.sbt$IvyActions$$resolve(IvyActions.scala:278)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:175)
    at sbt.IvyActions$$anonfun$updateEither$1.apply(IvyActions.scala:157)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$Module$$anonfun$withModule$1.apply(Ivy.scala:151)
    at sbt.IvySbt$$anonfun$withIvy$1.apply(Ivy.scala:128)
    at sbt.IvySbt.sbt$IvySbt$$action$1(Ivy.scala:56)
    at sbt.IvySbt$$anon$4.call(Ivy.scala:64)
    at xsbt.boot.Locks$GlobalLock.withChannel$1(Locks.scala:93)
    at xsbt.boot.Locks$GlobalLock.xsbt$boot$Locks$GlobalLock$$withChannelRetries$1(Locks.scala:78)
    at xsbt.boot.Locks$GlobalLock$$anonfun$withFileLock$1.apply(Locks.scala:97)
    at xsbt.boot.Using$.withResource(Using.scala:10)
    at xsbt.boot.Using$.apply(Using.scala:9)
    at xsbt.boot.Locks$GlobalLock.ignoringDeadlockAvoided(Locks.scala:58)
    at xsbt.boot.Locks$GlobalLock.withLock(Locks.scala:48)
    at xsbt.boot.Locks$.apply0(Locks.scala:31)
    at xsbt.boot.Locks$.apply(Locks.scala:28)
    at sbt.IvySbt.withDefaultLogger(Ivy.scala:64)
    at sbt.IvySbt.withIvy(Ivy.scala:123)
    at sbt.IvySbt.withIvy(Ivy.scala:120)
    at sbt.IvySbt$Module.withModule(Ivy.scala:151)
    at sbt.IvyActions$.updateEither(IvyActions.scala:157)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1318)
    at sbt.Classpaths$$anonfun$sbt$Classpaths$$work$1$1.apply(Defaults.scala:1315)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1345)
    at sbt.Classpaths$$anonfun$doWork$1$1$$anonfun$85.apply(Defaults.scala:1343)
    at sbt.Tracked$$anonfun$lastOutput$1.apply(Tracked.scala:35)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1348)
    at sbt.Classpaths$$anonfun$doWork$1$1.apply(Defaults.scala:1342)
    at sbt.Tracked$$anonfun$inputChanged$1.apply(Tracked.scala:45)
    at sbt.Classpaths$.cachedUpdate(Defaults.scala:1360)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1300)
    at sbt.Classpaths$$anonfun$updateTask$1.apply(Defaults.scala:1275)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
[error](*:update) sbt.ResolveException: unresolved dependency: com.lihaoyi#workbench;0.2.3: not found

**Comment by stewSquared** [comment]
I can't reproduce this.

**Comment by chrisalbright** [comment]
I experienced this as well... I was able to move past it by removing ~/.ivy2 and ~/.sbt after reading this thread: https://www.mail-archive.com/user@spark.apache.org/msg47035.html
