### ISSUE TITLE
todomvc branch - java.io.IOException: This version (0.6.6) of Scala.js IR is not supported. 

### ISSUE THREAD

**Issue by jhegedus42** [lihaoyi/workbench-example-app#35]
```
Jozsefs-MBP:workbench-example-app joco$ git status
On branch todomvc
Your branch is up-to-date with 'origin/todomvc'.
nothing to commit, working directory clean
Jozsefs-MBP:workbench-example-app joco$ sbt
[info] Loading global plugins from /Users/joco/.sbt/0.13/plugins
[info] Loading project definition from /Users/joco/dev/scala.js/workbench-example-app/project
[info] Set current project to Example (in build file:/Users/joco/dev/scala.js/workbench-example-app/)
> [INFO] [09/24/2016 19:23:20.652] [Workbench-System-akka.actor.default-dispatcher-4] [akka://Workbench-System/user/IO-HTTP/listener-0] Bound to localhost/127.0.0.1:12345
> fastOptJS
[warn] Scala version was updated by one of library dependencies:
[warn]  * org.scala-lang:scala-library:2.11.4 -> 2.11.5
[warn] To force scalaVersion, add the following:
[warn]  ivyScala := ivyScala.value map { _.copy(overrideScalaVersion = true) }
[warn] Run 'evicted' to see detailed eviction warnings
[info] Fast optimizing /Users/joco/dev/scala.js/workbench-example-app/target/scala-2.11/example-fastopt.js
[info] workbench: Checking example-fastopt.js
[info] workbench: Checking example-jsdeps.js
[info] workbench: Refreshing http://localhost:12345/target/scala-2.11/example-fastopt.js
[trace] Stack trace suppressed: run last compile:fastOptJS for the full output.
[error] (compile:fastOptJS) java.io.IOException: Failed to deserialize info of /Users/joco/dev/scala.js/workbench-example-app/target/scala-2.11/classes/example/Point$.sjsir
[error] Total time: 1 s, completed Sep 24, 2016 7:23:26 PM
> last compile:fastOptJS
[info] Fast optimizing /Users/joco/dev/scala.js/workbench-example-app/target/scala-2.11/example-fastopt.js
java.io.IOException: Failed to deserialize info of /Users/joco/dev/scala.js/workbench-example-app/target/scala-2.11/classes/example/Point$.sjsir
    at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile$class.info(VirtualFiles.scala:135)
    at org.scalajs.core.tools.io.FileVirtualScalaJSIRFile.info(FileVirtualFiles.scala:157)
    at org.scalajs.core.tools.optimizer.Linker$PersistentIRFile.updateFile(Linker.scala:309)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$16.apply(Linker.scala:271)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$16.apply(Linker.scala:268)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.scalajs.core.tools.optimizer.Linker.org$scalajs$core$tools$optimizer$Linker$$updateFiles(Linker.scala:268)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$1.apply(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$1.apply(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.package$.logTime(package.scala:19)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:106)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:106)
    at org.scalajs.core.tools.optimizer.package$.logTime(package.scala:19)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:105)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:89)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$optimizeCP$1.apply$mcV$sp(ScalaJSOptimizer.scala:65)
    at org.scalajs.core.tools.io.CacheUtils$.cached(CacheUtils.scala:41)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeCP(ScalaJSOptimizer.scala:63)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$14.apply(ScalaJSPluginInternal.scala:145)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$14.apply(ScalaJSPluginInternal.scala:129)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: This version (0.6.6) of Scala.js IR is not supported. Supported versions are: 0.6.0
    at org.scalajs.core.ir.InfoSerializers$Deserializer.readHeader(InfoSerializers.scala:149)
    at org.scalajs.core.ir.InfoSerializers$Deserializer.deserialize(InfoSerializers.scala:100)
    at org.scalajs.core.ir.InfoSerializers$.deserializeWithVersion(InfoSerializers.scala:35)
    at org.scalajs.core.ir.InfoSerializers$.deserialize(InfoSerializers.scala:31)
    at org.scalajs.core.tools.io.VirtualSerializedScalaJSIRFile$class.info(VirtualFiles.scala:132)
    at org.scalajs.core.tools.io.FileVirtualScalaJSIRFile.info(FileVirtualFiles.scala:157)
    at org.scalajs.core.tools.optimizer.Linker$PersistentIRFile.updateFile(Linker.scala:309)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$16.apply(Linker.scala:271)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$16.apply(Linker.scala:268)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:244)
    at scala.collection.immutable.List.foreach(List.scala:318)
    at scala.collection.TraversableLike$class.map(TraversableLike.scala:244)
    at scala.collection.AbstractTraversable.map(Traversable.scala:105)
    at org.scalajs.core.tools.optimizer.Linker.org$scalajs$core$tools$optimizer$Linker$$updateFiles(Linker.scala:268)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$1.apply(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.Linker$$anonfun$1.apply(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.package$.logTime(package.scala:19)
    at org.scalajs.core.tools.optimizer.Linker.link(Linker.scala:49)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:106)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$1.apply(ScalaJSOptimizer.scala:106)
    at org.scalajs.core.tools.optimizer.package$.logTime(package.scala:19)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:105)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeIR(ScalaJSOptimizer.scala:89)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer$$anonfun$optimizeCP$1.apply$mcV$sp(ScalaJSOptimizer.scala:65)
    at org.scalajs.core.tools.io.CacheUtils$.cached(CacheUtils.scala:41)
    at org.scalajs.core.tools.optimizer.ScalaJSOptimizer.optimizeCP(ScalaJSOptimizer.scala:63)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$14.apply(ScalaJSPluginInternal.scala:145)
    at org.scalajs.sbtplugin.ScalaJSPluginInternal$$anonfun$14.apply(ScalaJSPluginInternal.scala:129)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
    at sbt.std.Transform$$anon$4.work(System.scala:63)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
    at sbt.Execute.work(Execute.scala:235)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
[error] (compile:fastOptJS) java.io.IOException: Failed to deserialize info of /Users/joco/dev/scala.js/workbench-example-app/target/scala-2.11/classes/example/Point$.sjsir
>
```

**Comment by stewSquared** [comment]
Fixed in #37 Let's close this one.
